
name: Black Check

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Run Black
        uses: psf/black@stable
        with:
          options: "--check --diff --verbose"
          src: "."